name: Deploy develop to DockerHub

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths-ignore: 
      - '**.md'

jobs:
  build_publish_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Generate tag vars
      id: tagvars
      run: |
       echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
       echo "::set-output name=build_datetime::$(date -u +%Y%m%d-%H%M)"
      
    - name: Builder Dockerimage and publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: alb2k/fuel-filling-service
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "develop"
